# Simple Block Comparison Evaluation

This notebook compares **manual/reference JSON blocks** with **Llama/AI detected JSON blocks**.

It answers only three questions for each manual block:

1. **Did Llama find similar text?**
2. **Did Llama give the correct label?**
3. **Was it in the correct order?**

It also creates:

- overall summary per sample
- block-level comparison report
- per-label accuracy
- label confusion table
- unmatched/extra Llama blocks

## Step 1 — Import libraries

In [1]:
from pathlib import Path
import json
import re
from difflib import SequenceMatcher

import pandas as pd

pd.set_option('display.max_colwidth', 120)
pd.set_option('display.max_rows', 200)

## Step 2 — Set project folders

Update these folders only if your files are somewhere else.

Expected file names:

- `sample1_reference_blocks.json`
- `sample1_llama_blocks.json`

The code also handles names like `sample1_reference__blocks.json`.

In [2]:
# Find project root
cwd = Path.cwd()

if (cwd / 'data').exists():
    project_root = cwd
elif (cwd.parent / 'data').exists():
    project_root = cwd.parent
else:
    # Fallback for uploaded files in this environment
    project_root = Path('/mnt/data')

# Main folders
reference_dir = project_root / 'data' / 'reference_structure_blocks'
llama_dir = project_root / 'data' / 'llama_structured_blocks'

# If folders do not exist, use /mnt/data for uploaded sample files
if not reference_dir.exists():
    reference_dir = Path('/mnt/data')
if not llama_dir.exists():
    llama_dir = Path('/mnt/data')

output_dir = project_root / 'data' / 'block_comparison_reports_simple'
if project_root == Path('/mnt/data'):
    output_dir = Path('/mnt/data/block_comparison_reports_simple')

output_dir.mkdir(parents=True, exist_ok=True)

print('Project root:', project_root)
print('Reference folder:', reference_dir)
print('Llama folder:', llama_dir)
print('Output folder:', output_dir)

Project root: c:\Users\Nahid\dmpbridge
Reference folder: c:\Users\Nahid\dmpbridge\data\reference_structure_blocks
Llama folder: c:\Users\Nahid\dmpbridge\data\llama_structured_blocks
Output folder: c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple

## Step 3 — Find JSON files

In [4]:
reference_files = sorted(reference_dir.glob('*reference*blocks*.json'))
llama_files = sorted(llama_dir.glob('*llama*blocks*.json'))

print('Reference files:')
for f in reference_files:
    print(' -', f.name)

print('Llama files:')
for f in llama_files:
    print(' -', f.name)

Reference files:
 - sample10_reference_blocks.json
 - sample1_reference_blocks.json
 - sample2_reference_blocks.json
 - sample3_reference_blocks.json
 - sample4_reference_blocks.json
 - sample5_reference_blocks.json
 - sample6_reference_blocks.json
 - sample7_reference_blocks.json
 - sample8_reference_blocks.json
 - sample9_reference_blocks.json
Llama files:
 - sample10_llama_blocks.json
 - sample1_llama_blocks.json
 - sample2_llama_blocks.json
 - sample3_llama_blocks.json
 - sample4_llama_blocks.json
 - sample5_llama_blocks.json
 - sample6_llama_blocks.json
 - sample7_llama_blocks.json
 - sample8_llama_blocks.json
 - sample9_llama_blocks.json

## Step 4 — Helper functions

These functions keep the comparison simple:

- clean text before matching
- extract sample ID from file name
- compute text similarity
- load JSON blocks

In [6]:
def normalize_text(text):
    """Clean text so small formatting differences do not hurt matching."""
    if text is None:
        return ''
    text = str(text)
    text = text.replace(' ', ' ').replace('	', ' ')
    text = text.replace('“', '"').replace('”', '"').replace('’', "'")
    text = text.replace('–', '-').replace('—', '-')
    text = re.sub(r'\s+', ' ', text)
    return text.strip().lower()


def token_set_similarity(a, b):
    """Word overlap similarity between two text blocks."""
    a_tokens = set(normalize_text(a).split())
    b_tokens = set(normalize_text(b).split())
    if not a_tokens or not b_tokens:
        return 0.0
    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)


def sequence_similarity(a, b):
    """Character/order similarity between two text blocks."""
    return SequenceMatcher(None, normalize_text(a), normalize_text(b)).ratio()


def combined_similarity(a, b):
    """Final text similarity score: 60% sequence + 40% word overlap."""
    return (0.60 * sequence_similarity(a, b)) + (0.40 * token_set_similarity(a, b))


def sample_id_from_filename(path):
    """Extract sample ID from a file name."""
    name = path.stem.lower()
    name = name.replace('_reference__blocks', '')
    name = name.replace('_reference_blocks', '')
    name = name.replace('_llama_blocks', '')
    name = name.replace('-reference-blocks', '')
    name = name.replace('-llama-blocks', '')
    return name


def load_blocks(json_path):
    """Load blocks from JSON and keep only index, label, text."""
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Some JSON files may store blocks inside a dictionary
    if isinstance(data, dict):
        for key in ['blocks', 'structured_blocks', 'data']:
            if key in data and isinstance(data[key], list):
                data = data[key]
                break

    blocks = []
    for i, block in enumerate(data, start=1):
        if not isinstance(block, dict):
            continue
        label = str(block.get('label', '')).strip()
        text = str(block.get('text', '')).strip()
        if not text:
            continue
        blocks.append({
            'idx': i,
            'label': label,
            'text': text,
            'norm_text': normalize_text(text)
        })
    return blocks

## Step 5 — Set simple evaluation rules

A block is counted as **text found** when similarity is at least `SIMILARITY_THRESHOLD`.

A block is counted as **order correct** when the reference index and Llama index are within `ORDER_TOLERANCE` positions.

In [8]:
SIMILARITY_THRESHOLD = 0.75
ORDER_TOLERANCE = 1

print('Similarity threshold:', SIMILARITY_THRESHOLD)
print('Order tolerance:', ORDER_TOLERANCE)

Similarity threshold: 0.75
Order tolerance: 1

## Step 6 — Compare one sample

In [9]:
def make_error_type(similar_text_found, label_correct, order_correct):
    """Simple explanation for each reference block."""
    if not similar_text_found:
        return 'text_not_found'
    if similar_text_found and not label_correct:
        return 'label_wrong'
    if similar_text_found and label_correct and not order_correct:
        return 'order_wrong'
    return 'correct'


def compare_sample(sample_id, reference_path, llama_path,
                   similarity_threshold=SIMILARITY_THRESHOLD,
                   order_tolerance=ORDER_TOLERANCE):
    """Compare one reference JSON file with one Llama JSON file."""

    reference_blocks = load_blocks(reference_path)
    llama_blocks = load_blocks(llama_path)

    used_llama_indices = set()
    rows = []

    for ref in reference_blocks:
        best = None
        best_score = -1

        # Find best unused Llama block by text similarity
        for llama in llama_blocks:
            if llama['idx'] in used_llama_indices:
                continue

            score = combined_similarity(ref['text'], llama['text'])
            if score > best_score:
                best_score = score
                best = llama

        similar_text_found = best is not None and best_score >= similarity_threshold

        if similar_text_found:
            used_llama_indices.add(best['idx'])

            label_correct = ref['label'] == best['label']
            order_difference = abs(ref['idx'] - best['idx'])
            order_correct = order_difference <= order_tolerance

            llama_idx = best['idx']
            llama_label = best['label']
            llama_text = best['text']
        else:
            label_correct = False
            order_difference = None
            order_correct = False
            llama_idx = None
            llama_label = None
            llama_text = None

        rows.append({
            'sample_id': sample_id,
            'ref_idx': ref['idx'],
            'ref_label': ref['label'],
            'ref_text': ref['text'],
            'llama_idx': llama_idx,
            'llama_label': llama_label,
            'llama_text': llama_text,
            'similarity_score': round(best_score, 3) if best_score >= 0 else None,
            'similar_text_found': similar_text_found,
            'label_correct': label_correct,
            'order_difference': order_difference,
            'order_correct': order_correct,
            'error_type': make_error_type(similar_text_found, label_correct, order_correct)
        })

    # Extra Llama blocks: detected by Llama but not matched to any reference block
    extra_rows = []
    for llama in llama_blocks:
        if llama['idx'] not in used_llama_indices:
            extra_rows.append({
                'sample_id': sample_id,
                'llama_idx': llama['idx'],
                'llama_label': llama['label'],
                'llama_text': llama['text'],
                'issue': 'extra_or_unmatched_llama_block'
            })

    block_report = pd.DataFrame(rows)
    extra_report = pd.DataFrame(extra_rows)

    return block_report, extra_report, reference_blocks, llama_blocks

## Step 7 — Match reference files with Llama files

In [11]:
reference_map = {sample_id_from_filename(f): f for f in reference_files}
llama_map = {sample_id_from_filename(f): f for f in llama_files}

common_sample_ids = sorted(set(reference_map) & set(llama_map))

print('Matched sample IDs:')
for sid in common_sample_ids:
    print(' -', sid)

missing_llama = sorted(set(reference_map) - set(llama_map))
missing_reference = sorted(set(llama_map) - set(reference_map))

if missing_llama: print('Reference files without matching Llama file:', missing_llama)
if missing_reference:
    print('Llama files without matching reference file:', missing_reference)

Matched sample IDs:
 - sample1
 - sample10
 - sample2
 - sample3
 - sample4
 - sample5
 - sample6
 - sample7
 - sample8
 - sample9

## Step 8 — Run comparison for all samples

In [12]:
all_block_reports = []
all_extra_reports = []
summary_rows = []

for sample_id in common_sample_ids:
    block_report, extra_report, reference_blocks, llama_blocks = compare_sample(
        sample_id,
        reference_map[sample_id],
        llama_map[sample_id]
    )

    all_block_reports.append(block_report)
    all_extra_reports.append(extra_report)

    total_ref = len(reference_blocks)
    total_llama = len(llama_blocks)

    text_found = int(block_report['similar_text_found'].sum())
    label_correct = int(block_report['label_correct'].sum())
    order_correct = int(block_report['order_correct'].sum())
    wrong_or_missing = int((block_report['error_type'] != 'correct').sum())

    summary_rows.append({
        'sample_id': sample_id,
        'reference_blocks': total_ref,
        'llama_blocks': total_llama,
        'text_found': text_found,
        'label_correct': label_correct,
        'order_correct': order_correct,
        'wrong_or_missing': wrong_or_missing,
        'extra_llama_blocks': len(extra_report),
        'text_match_rate': round(text_found / total_ref, 3) if total_ref else 0,
        'label_accuracy': round(label_correct / total_ref, 3) if total_ref else 0,
        'order_accuracy': round(order_correct / total_ref, 3) if total_ref else 0
    })

block_level_report = pd.concat(all_block_reports, ignore_index=True) if all_block_reports else pd.DataFrame()
extra_llama_report = pd.concat(all_extra_reports, ignore_index=True) if all_extra_reports else pd.DataFrame()
summary_report = pd.DataFrame(summary_rows)

summary_report

,sample_id,reference_blocks,llama_blocks,text_found,label_correct,order_correct,wrong_or_missing,extra_llama_blocks,text_match_rate,label_accuracy,order_accuracy
0,sample1,26,28,26,23,24,5,2,1.000,0.885,0.923
1,sample10,13,13,13,13,13,0,0,1.000,1.000,1.000
2,sample2,12,32,5,5,2,10,27,0.417,0.417,0.167
3,sample3,14,9,7,7,1,13,2,0.500,0.500,0.071
4,sample4,2,26,1,1,1,1,25,0.500,0.500,0.500
5,sample5,13,25,9,9,1,12,16,0.692,0.692,0.077
6,sample6,11,11,3,3,3,8,8,0.273,0.273,0.273
7,sample7,2,2,2,2,2,0,0,1.000,1.000,1.000
8,sample8,13,13,13,13,13,0,0,1.000,1.000,1.000
9,sample9,11,14,11,10,7,4,3,1.000,0.909,0.636

## Step 9 — Block-level report

This is the most important table. Each row is one manual/reference block.

Look at:

- `similar_text_found`
- `label_correct`
- `order_correct`
- `error_type`

In [13]:
display_cols = [
    'sample_id', 'ref_idx', 'ref_label', 'llama_idx', 'llama_label',
    'similarity_score', 'similar_text_found', 'label_correct',
    'order_difference', 'order_correct', 'error_type', 'ref_text', 'llama_text'
]

block_level_report[display_cols]

,sample_id,ref_idx,ref_label,llama_idx,llama_label,similarity_score,similar_text_found,label_correct,order_difference,order_correct,error_type,ref_text,llama_text
0,sample1,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,DATA MANAGEMENT AND SHARING PLAN,DATA MANAGEMENT AND SHARING PLAN
1,sample1,2,section,2.0,section,1.000,True,True,0.0,True,correct,Element 1: Data Type:,Element 1: Data Type:
2,sample1,3,subsection,3.0,subsection,1.000,True,True,0.0,True,correct,A. Types and amount of scientific data expected to be generated in the project:,A. Types and amount of scientific data expected to be generated in the project:
3,sample1,4,content,4.0,content,0.981,True,True,0.0,True,correct,"This secondary data analysis project will analyze deidentified data from 48,218 participants from eight studies and ...","This secondary data analysis project will analyze deidentified data from 48,218 participants from eight studies and ..."
4,sample1,5,subsection,5.0,section,1.000,True,False,0.0,True,label_wrong,"B. Scientific data that will be preserved and shared, and the rationale for doing so:","B. Scientific data that will be preserved and shared, and the rationale for doing so:"
5,sample1,6,content,6.0,content,0.959,True,True,0.0,True,correct,"As this is a secondary data analysis project, we will only be able to publicly share in the UC San Diego Library Rep...","As this is a secondary data analysis project, we will only be able to publicly share in the UC San Diego Library Rep..."
6,sample1,7,subsection,7.0,section,1.000,True,False,0.0,True,label_wrong,"C. Metadata, other relevant data, and associated documentation:","C. Metadata, other relevant data, and associated documentation:"
7,sample1,8,content,8.0,content,1.000,True,True,0.0,True,correct,"In addition to the data described above, code and models will be included in the repository and in on our project’s ...","In addition to the data described above, code and models will be included in the repository and in on our project’s ..."
8,sample1,9,section,9.0,section,1.000,True,True,0.0,True,correct,"Element 2: Related Tools, Software and/or Code:","Element 2: Related Tools, Software and/or Code:"
9,sample1,10,content,10.0,content,1.000,True,True,0.0,True,correct,Data will be analyzed with custom code by our statistical and computer science team. ActiGraph data will be processe...,Data will be analyzed with custom code by our statistical and computer science team. ActiGraph data will be processe...
10,sample1,11,section,11.0,section,1.000,True,True,0.0,True,correct,Element 3: Standards:,Element 3: Standards:
11,sample1,12,content,12.0,content,0.940,True,True,0.0,True,correct,The following data will be created as a result of this project:Objective sedentary behavior metrics – no existing st...,The following data will be created as a result of this project:\n\nObjective sedentary behavior metrics – no existin...
12,sample1,13,section,13.0,section,1.000,True,True,0.0,True,correct,"Element 4: Data Preservation, Access, and Associated Timelines:","Element 4: Data Preservation, Access, and Associated Timelines:"
13,sample1,14,subsection,14.0,subsection,1.000,True,True,0.0,True,correct,A. Repository where scientific data and metadata will be archived:,A. Repository where scientific data and metadata will be archived:
14,sample1,15,content,15.0,content,1.000,True,True,0.0,True,correct,De-identified data will be uploaded to the University of California San Diego Library repository.,De-identified data will be uploaded to the University of California San Diego Library repository.
15,sample1,16,subsection,16.0,subsection,1.000,True,True,0.0,True,correct,B. How scientific data will be findable and identifiable:,B. How scientific data will be findable and identifiable:
16,sample1,17,content,17.0,content,1.000,True,True,0.0,True,correct,"Data will be findable via publications and on our project’s GitHub website, hosted as part of the UCSD Advance Data ...","Data will be findable via publications and on our project’s GitHub website, hosted as part of the UCSD Advance Data ..."
17,sample1,18,subsection,18.0,subsection,1.000,True,True,0.0,True,correct,C. When and how long the scientific data will be made available:,C. When and how long the scientific data will be made available:
18,sample1,19,content,19.0,content,0.982,True,True,0.0,True,correct,"The research community will have access to data when the main outcome manuscript has been published.$2,500 in years ...","The research community will have access to data when the main outcome manuscript has been published.\n\n$2,500 in ye..."
19,sample1,20,section,20.0,section,1.000,True,True,0.0,True,correct,"Element 5: Access, Distribution, or Reuse Considerations:","Element 5: Access, Distribution, or Reuse Considerations:"
20,sample1,21,subsection,21.0,subsection,1.000,True,True,0.0,True,correct,"A. Factors affecting subsequent access, distribution, or reuse of scientific data:","A. Factors affecting subsequent access, distribution, or reuse of scientific data:"
21,sample1,22,content,22.0,content,0.983,True,True,0.0,True,correct,The following studies have independent data use agreement & approved paper proposal processes for use of their data ...,The following studies have independent data use agreement & approved paper proposal processes for use of their data ...
22,sample1,23,subsection,23.0,section,1.000,True,False,0.0,True,label_wrong,B. Whether access to scientific data will be controlled:,B. Whether access to scientific data will be controlled:
23,sample1,24,content,24.0,content,0.784,True,True,0.0,True,correct,"The final dataset of data from the RISE study, the iWATCH study, and NHANES cohorts will be de-identified. It will b...","The final dataset of data from the RISE study, the iWATCH study, and NHANES cohorts will be de-identified. It will b..."
24,sample1,25,section,27.0,section,1.000,True,True,2.0,False,order_wrong,Element 6: Oversight of Data Management and Sharing:,Element 6: Oversight of Data Management and Sharing:
25,sample1,26,content,28.0,content,1.000,True,True,2.0,False,order_wrong,"The PI and Trial & IRB Coordinator will provide updates and changes to the plan in the annual RPPR. The PI, Trial & ...","The PI and Trial & IRB Coordinator will provide updates and changes to the plan in the annual RPPR. The PI, Trial & ..."
26,sample10,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,DATA MANAGEMENT,DATA MANAGEMENT
27,sample10,2,section,2.0,section,1.000,True,True,0.0,True,correct,1. Policy and Practice,1. Policy and Practice
28,sample10,3,content,3.0,content,1.000,True,True,0.0,True,correct,We will ensure that the data obtained and this study will be made available to the research community. The Bourns Co...,We will ensure that the data obtained and this study will be made available to the research community.\n\nThe Bourns...
29,sample10,4,section,4.0,section,1.000,True,True,0.0,True,correct,2. Scope,2. Scope
30,sample10,5,content,5.0,content,1.000,True,True,0.0,True,correct,This Data Management Plan addresses the NSF policy that primary data “commonly accepted in the scientific community ...,This Data Management Plan addresses the NSF policy that primary data “commonly accepted in the scientific community ...
31,sample10,6,section,6.0,section,1.000,True,True,0.0,True,correct,3. Data and Metadata Format and Contents,3. Data and Metadata Format and Contents
32,sample10,7,content,7.0,content,1.000,True,True,0.0,True,correct,We will make the proposed nano-vesicles (NETs) available to interested investigators who would like to use them in t...,We will make the proposed nano-vesicles (NETs) available to interested investigators who would like to use them in t...
33,sample10,8,section,8.0,section,1.000,True,True,0.0,True,correct,4. Accessibility and Data Protection,4. Accessibility and Data Protection
34,sample10,9,content,9.0,content,1.000,True,True,0.0,True,correct,"Materials will be searchable through a number of databases and search engines, including Google and Google Scholar. ...","Materials will be searchable through a number of databases and search engines, including Google and Google Scholar. ..."
35,sample10,10,section,10.0,section,1.000,True,True,0.0,True,correct,5. Derivative Products,5. Derivative Products
36,sample10,11,content,11.0,content,1.000,True,True,0.0,True,correct,All materials will contain acknowledgement of NSF support as per NSF policy: “ This material is based upon work supp...,All materials will contain acknowledgement of NSF support as per NSF policy: “ This material is based upon work supp...
37,sample10,12,section,12.0,section,1.000,True,True,0.0,True,correct,6. Archiving and Access,6. Archiving and Access
38,sample10,13,content,13.0,content,1.000,True,True,0.0,True,correct,It is understood that the NSF Engineering Directorate requires data to be made available for a minimum of three year...,It is understood that the NSF Engineering Directorate requires data to be made available for a minimum of three year...
39,sample2,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,Center for Bio-Inspired Energy Science,Center for Bio-Inspired Energy Science
40,sample2,2,section,2.0,section,1.000,True,True,0.0,True,correct,1. Data sharing and preservation,1. Data sharing and preservation
41,sample2,3,subsection,NaN,None,0.671,False,False,NaN,False,text_not_found,Data management plans should describe whether and how data generated in the course of the proposed research will be ...,None
42,sample2,4,content,NaN,None,0.570,False,False,NaN,False,text_not_found,"Roles & Responsibilities. For the proposed research, Director Samuel Stupp with help from the Executive Director of ...",None
43,sample2,5,section,15.0,section,1.000,True,True,10.0,False,order_wrong,2. Data used in publications,2. Data used in publications
44,sample2,6,subsection,NaN,None,0.200,False,False,NaN,False,text_not_found,Data management plans should describe how data used in publications resulting from the proposed research will be mad...,None
45,sample2,7,content,NaN,None,0.697,False,False,NaN,False,text_not_found,Research conducted within the Center will be published in appropriate scientific journals. The publisher may restric...,None
46,sample2,8,section,20.0,section,1.000,True,True,12.0,False,order_wrong,3. Data management resources,3. Data management resources
47,sample2,9,subsection,NaN,None,0.403,False,False,NaN,False,text_not_found,Data management plans should consult and reference available information about data management resources to be used ...,None
48,sample2,10,content,NaN,None,0.470,False,False,NaN,False,text_not_found,DMPs should consult and reference available information about data management resources to be used in the course of ...,None
49,sample2,11,section,29.0,section,1.000,True,True,18.0,False,order_wrong,"4. Confidentiality, security and rights","4. Confidentiality, security and rights"
50,sample2,12,content,NaN,None,0.622,False,False,NaN,False,text_not_found,"Data management plans must protect confidentiality, personal privacy, Personally Identifiable Information and U.S. n...",None
51,sample3,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,CPS 2015,CPS 2015
52,sample3,2,section,NaN,None,0.308,False,False,NaN,False,text_not_found,Roles and responsibilities,None
53,sample3,3,subsection,NaN,None,0.618,False,False,NaN,False,text_not_found,The Data Management Plan should clearly articulate how the PI and co-PIs plan to manage and disseminate data generat...,None
54,sample3,4,content,NaN,None,0.635,False,False,NaN,False,text_not_found,Data will be generated at each of our institutional sites. The PI at each institution will be responsible for follow...,None
55,sample3,5,section,3.0,section,1.000,True,True,2.0,False,order_wrong,Types of data,Types of data
56,sample3,6,subsection,NaN,None,0.395,False,False,NaN,False,text_not_found,"The Data Management Plan should describe the types of data, samples, physical collections, software, curriculum mate...",None
57,sample3,7,content,4.0,content,0.800,True,True,3.0,False,order_wrong,We will manage all scientific and technical content generated from this proposal. Our products will include 3 broad ...,"The Data Management Plan should describe the types of data, samples, physical collections, software, curriculum mate..."
58,sample3,8,section,5.0,section,1.000,True,True,3.0,False,order_wrong,Policies for access and sharing and appropriate protection and privacy,Policies for access and sharing and appropriate protection and privacy
59,sample3,9,subsection,NaN,None,0.278,False,False,NaN,False,text_not_found,The Data Management Plan should describe the period of time the data will be retained and shared; factors that limit...,None
60,sample3,10,content,6.0,content,0.863,True,True,4.0,False,order_wrong,"Data will be made available upon request, after the conclusion of each of study. The availability of data (raw and a...",The Data Management Plan should describe the period of time the data will be retained and shared; factors that limit...
61,sample3,11,section,7.0,section,1.000,True,True,4.0,False,order_wrong,Data storage and preservation of access,Data storage and preservation of access
62,sample3,12,subsection,NaN,None,0.519,False,False,NaN,False,text_not_found,The Data Management Plan should describe the mechanisms and formats for storing data and making them accessible to o...,None
63,sample3,13,content,NaN,None,0.710,False,False,NaN,False,text_not_found,The servers at the Rehabilitation Institute of Chicago will serve as the central repository for all collected data. ...,None
64,sample3,14,section,9.0,section,1.000,True,True,5.0,False,order_wrong,Additional possible data management requirements,Additional possible data management requirements
65,sample4,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,DATA MANAGEMENT PLAN,DATA MANAGEMENT PLAN
66,sample4,2,content,NaN,None,0.269,False,False,NaN,False,text_not_found,The P.I. has completed human subjects training. The research assistants will be required to complete human subjects ...,None
67,sample5,1,document_title,NaN,None,0.669,False,False,NaN,False,text_not_found,DATA MANAGEMENT PLAN REVIEW OF PROPOSAL COMPONENTS,None
68,sample5,2,section,2.0,section,1.000,True,True,0.0,True,correct,REVIEW OF PROPOSAL COMPONENTS,REVIEW OF PROPOSAL COMPONENTS
69,sample5,3,content,NaN,None,0.615,False,False,NaN,False,text_not_found,The proposal is separated into three sections. Section 2.1 characterizes the aquifer formation that each groundwater...,None
70,sample5,4,section,6.0,section,1.000,True,True,2.0,False,order_wrong,TYPES OF DATA,TYPES OF DATA
71,sample5,5,content,NaN,None,0.593,False,False,NaN,False,text_not_found,"The PI and PhD student will be responsible for all data-related activities including: collection, documentation and ...",None
72,sample5,6,section,12.0,section,1.000,True,True,6.0,False,order_wrong,DATA AND METADATA STANDARDS,DATA AND METADATA STANDARDS
73,sample5,7,content,13.0,content,1.000,True,True,6.0,False,order_wrong,"The data will be shared along with a README.txt, which will describe all files, their relationships, naming conventi...","The data will be shared along with a README.txt, which will describe all files, their relationships, naming conventi..."
74,sample5,8,section,14.0,section,1.000,True,True,6.0,False,order_wrong,POLICIES FOR ACCESS AND SHARING,POLICIES FOR ACCESS AND SHARING
75,sample5,9,content,NaN,None,0.672,False,False,NaN,False,text_not_found,"Raw data: Detailed information about how the data were obtained, including detailed contact information or websites ...",None
76,sample5,10,section,22.0,section,1.000,True,True,12.0,False,order_wrong,"POLICIES AND PROVISIONS FOR RE-USE, RE-DISTRIBUTION","POLICIES AND PROVISIONS FOR RE-USE, RE-DISTRIBUTION"
77,sample5,11,content,23.0,content,1.000,True,True,12.0,False,order_wrong,"All data deposited at Dryad will be publicly available under a CC0 license, meaning that others may freely build upo...","All data deposited at Dryad will be publicly available under a CC0 license, meaning that others may freely build upo..."
78,sample5,12,section,24.0,section,1.000,True,True,12.0,False,order_wrong,PLANS FOR ARCHIVING AND PRESERVATION OF ACCESS,PLANS FOR ARCHIVING AND PRESERVATION OF ACCESS
79,sample5,13,content,25.0,content,1.000,True,True,12.0,False,order_wrong,"UCSB Box will be used as the primary means to store and back up all collected input, generated output data sets and ...","UCSB Box will be used as the primary means to store and back up all collected input, generated output data sets and ..."
80,sample6,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,Data Management Plan:,Data Management Plan:
81,sample6,2,section,NaN,None,0.285,False,False,NaN,False,text_not_found,1. Types of data.,None
82,sample6,3,content,3.0,content,0.867,True,True,0.0,True,correct,"The bulk of the data generated in this project will be 1, 2, 3, and 4 dimensional arrays of numbers and bytes repres...",dimensional arrays of numbers and bytes representing fluid state variables generated via computer simulations of flu...
83,sample6,4,section,NaN,None,0.493,False,False,NaN,False,text_not_found,2. Data and metadata standards.,None
84,sample6,5,content,NaN,None,0.365,False,False,NaN,False,text_not_found,The PI’s research group will adopt the longstanding practice that all generated data should be straightforwardly rep...,None
85,sample6,6,section,NaN,None,0.471,False,False,NaN,False,text_not_found,3. Policies for access and sharing.,None
86,sample6,7,content,NaN,None,0.739,False,False,NaN,False,text_not_found,Interested parties will be able to request data and codes at the end of the project. Such parties will be responsibl...,None
87,sample6,8,section,NaN,None,0.640,False,False,NaN,False,text_not_found,"4. Policies and provisions for re-use, re-distribution.",None
88,sample6,9,content,NaN,None,0.388,False,False,NaN,False,text_not_found,Simulation data will in essence grow to several terrabytes with an associated cost of storage. Data will be made pub...,None
89,sample6,10,section,NaN,None,0.620,False,False,NaN,False,text_not_found,5. Plans for archiving and preservation of access.,None
90,sample6,11,content,11.0,content,0.928,True,True,0.0,True,correct,"Local data will be archived on the group’s mass storage system. As mentioned above, all data generated is archived w...","mass storage system. As mentioned above, all data generated is archived with the entire code that generated it. Addi..."
91,sample7,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,Resource/Data Sharing Plan,Resource/Data Sharing Plan
92,sample7,2,content,2.0,content,0.992,True,True,0.0,True,correct,The study investigators are committed to the open and timely dissemination of study data. The final datasets will in...,The study investigators are committed to the open and timely dissemination of study data. The final datasets will in...
93,sample8,1,document_title,1.0,document_title,1.000,True,True,0.0,True,correct,"Univ. of California, Riverside Data Management Plan","Univ. of California, Riverside Data Management Plan"
94,sample8,2,section,2.0,section,1.000,True,True,0.0,True,correct,1. Policy and Practice,1. Policy and Practice
95,sample8,3,content,3.0,content,1.000,True,True,0.0,True,correct,"The Bourns College of Engineering (BCOE) at the University of California, Riverside , in partnership with the UCR Li...","The Bourns College of Engineering (BCOE) at the University of California, Riverside , in partnership with the UCR Li..."
96,sample8,4,section,4.0,section,1.000,True,True,0.0,True,correct,2. Scope,2. Scope

## Step 10 — Show only problem blocks

This table makes it easy to see **which blocks were wrong**.

In [14]:
problem_blocks = block_level_report[block_level_report['error_type'] != 'correct'].copy()
problem_blocks[display_cols]

,sample_id,ref_idx,ref_label,llama_idx,llama_label,similarity_score,similar_text_found,label_correct,order_difference,order_correct,error_type,ref_text,llama_text
4,sample1,5,subsection,5.0,section,1.000,True,False,0.0,True,label_wrong,"B. Scientific data that will be preserved and shared, and the rationale for doing so:","B. Scientific data that will be preserved and shared, and the rationale for doing so:"
6,sample1,7,subsection,7.0,section,1.000,True,False,0.0,True,label_wrong,"C. Metadata, other relevant data, and associated documentation:","C. Metadata, other relevant data, and associated documentation:"
22,sample1,23,subsection,23.0,section,1.000,True,False,0.0,True,label_wrong,B. Whether access to scientific data will be controlled:,B. Whether access to scientific data will be controlled:
24,sample1,25,section,27.0,section,1.000,True,True,2.0,False,order_wrong,Element 6: Oversight of Data Management and Sharing:,Element 6: Oversight of Data Management and Sharing:
25,sample1,26,content,28.0,content,1.000,True,True,2.0,False,order_wrong,"The PI and Trial & IRB Coordinator will provide updates and changes to the plan in the annual RPPR. The PI, Trial & ...","The PI and Trial & IRB Coordinator will provide updates and changes to the plan in the annual RPPR. The PI, Trial & ..."
41,sample2,3,subsection,NaN,None,0.671,False,False,NaN,False,text_not_found,Data management plans should describe whether and how data generated in the course of the proposed research will be ...,None
42,sample2,4,content,NaN,None,0.570,False,False,NaN,False,text_not_found,"Roles & Responsibilities. For the proposed research, Director Samuel Stupp with help from the Executive Director of ...",None
43,sample2,5,section,15.0,section,1.000,True,True,10.0,False,order_wrong,2. Data used in publications,2. Data used in publications
44,sample2,6,subsection,NaN,None,0.200,False,False,NaN,False,text_not_found,Data management plans should describe how data used in publications resulting from the proposed research will be mad...,None
45,sample2,7,content,NaN,None,0.697,False,False,NaN,False,text_not_found,Research conducted within the Center will be published in appropriate scientific journals. The publisher may restric...,None
46,sample2,8,section,20.0,section,1.000,True,True,12.0,False,order_wrong,3. Data management resources,3. Data management resources
47,sample2,9,subsection,NaN,None,0.403,False,False,NaN,False,text_not_found,Data management plans should consult and reference available information about data management resources to be used ...,None
48,sample2,10,content,NaN,None,0.470,False,False,NaN,False,text_not_found,DMPs should consult and reference available information about data management resources to be used in the course of ...,None
49,sample2,11,section,29.0,section,1.000,True,True,18.0,False,order_wrong,"4. Confidentiality, security and rights","4. Confidentiality, security and rights"
50,sample2,12,content,NaN,None,0.622,False,False,NaN,False,text_not_found,"Data management plans must protect confidentiality, personal privacy, Personally Identifiable Information and U.S. n...",None
52,sample3,2,section,NaN,None,0.308,False,False,NaN,False,text_not_found,Roles and responsibilities,None
53,sample3,3,subsection,NaN,None,0.618,False,False,NaN,False,text_not_found,The Data Management Plan should clearly articulate how the PI and co-PIs plan to manage and disseminate data generat...,None
54,sample3,4,content,NaN,None,0.635,False,False,NaN,False,text_not_found,Data will be generated at each of our institutional sites. The PI at each institution will be responsible for follow...,None
55,sample3,5,section,3.0,section,1.000,True,True,2.0,False,order_wrong,Types of data,Types of data
56,sample3,6,subsection,NaN,None,0.395,False,False,NaN,False,text_not_found,"The Data Management Plan should describe the types of data, samples, physical collections, software, curriculum mate...",None
57,sample3,7,content,4.0,content,0.800,True,True,3.0,False,order_wrong,We will manage all scientific and technical content generated from this proposal. Our products will include 3 broad ...,"The Data Management Plan should describe the types of data, samples, physical collections, software, curriculum mate..."
58,sample3,8,section,5.0,section,1.000,True,True,3.0,False,order_wrong,Policies for access and sharing and appropriate protection and privacy,Policies for access and sharing and appropriate protection and privacy
59,sample3,9,subsection,NaN,None,0.278,False,False,NaN,False,text_not_found,The Data Management Plan should describe the period of time the data will be retained and shared; factors that limit...,None
60,sample3,10,content,6.0,content,0.863,True,True,4.0,False,order_wrong,"Data will be made available upon request, after the conclusion of each of study. The availability of data (raw and a...",The Data Management Plan should describe the period of time the data will be retained and shared; factors that limit...
61,sample3,11,section,7.0,section,1.000,True,True,4.0,False,order_wrong,Data storage and preservation of access,Data storage and preservation of access
62,sample3,12,subsection,NaN,None,0.519,False,False,NaN,False,text_not_found,The Data Management Plan should describe the mechanisms and formats for storing data and making them accessible to o...,None
63,sample3,13,content,NaN,None,0.710,False,False,NaN,False,text_not_found,The servers at the Rehabilitation Institute of Chicago will serve as the central repository for all collected data. ...,None
64,sample3,14,section,9.0,section,1.000,True,True,5.0,False,order_wrong,Additional possible data management requirements,Additional possible data management requirements
66,sample4,2,content,NaN,None,0.269,False,False,NaN,False,text_not_found,The P.I. has completed human subjects training. The research assistants will be required to complete human subjects ...,None
67,sample5,1,document_title,NaN,None,0.669,False,False,NaN,False,text_not_found,DATA MANAGEMENT PLAN REVIEW OF PROPOSAL COMPONENTS,None
69,sample5,3,content,NaN,None,0.615,False,False,NaN,False,text_not_found,The proposal is separated into three sections. Section 2.1 characterizes the aquifer formation that each groundwater...,None
70,sample5,4,section,6.0,section,1.000,True,True,2.0,False,order_wrong,TYPES OF DATA,TYPES OF DATA
71,sample5,5,content,NaN,None,0.593,False,False,NaN,False,text_not_found,"The PI and PhD student will be responsible for all data-related activities including: collection, documentation and ...",None
72,sample5,6,section,12.0,section,1.000,True,True,6.0,False,order_wrong,DATA AND METADATA STANDARDS,DATA AND METADATA STANDARDS
73,sample5,7,content,13.0,content,1.000,True,True,6.0,False,order_wrong,"The data will be shared along with a README.txt, which will describe all files, their relationships, naming conventi...","The data will be shared along with a README.txt, which will describe all files, their relationships, naming conventi..."
74,sample5,8,section,14.0,section,1.000,True,True,6.0,False,order_wrong,POLICIES FOR ACCESS AND SHARING,POLICIES FOR ACCESS AND SHARING
75,sample5,9,content,NaN,None,0.672,False,False,NaN,False,text_not_found,"Raw data: Detailed information about how the data were obtained, including detailed contact information or websites ...",None
76,sample5,10,section,22.0,section,1.000,True,True,12.0,False,order_wrong,"POLICIES AND PROVISIONS FOR RE-USE, RE-DISTRIBUTION","POLICIES AND PROVISIONS FOR RE-USE, RE-DISTRIBUTION"
77,sample5,11,content,23.0,content,1.000,True,True,12.0,False,order_wrong,"All data deposited at Dryad will be publicly available under a CC0 license, meaning that others may freely build upo...","All data deposited at Dryad will be publicly available under a CC0 license, meaning that others may freely build upo..."
78,sample5,12,section,24.0,section,1.000,True,True,12.0,False,order_wrong,PLANS FOR ARCHIVING AND PRESERVATION OF ACCESS,PLANS FOR ARCHIVING AND PRESERVATION OF ACCESS
79,sample5,13,content,25.0,content,1.000,True,True,12.0,False,order_wrong,"UCSB Box will be used as the primary means to store and back up all collected input, generated output data sets and ...","UCSB Box will be used as the primary means to store and back up all collected input, generated output data sets and ..."
81,sample6,2,section,NaN,None,0.285,False,False,NaN,False,text_not_found,1. Types of data.,None
83,sample6,4,section,NaN,None,0.493,False,False,NaN,False,text_not_found,2. Data and metadata standards.,None
84,sample6,5,content,NaN,None,0.365,False,False,NaN,False,text_not_found,The PI’s research group will adopt the longstanding practice that all generated data should be straightforwardly rep...,None
85,sample6,6,section,NaN,None,0.471,False,False,NaN,False,text_not_found,3. Policies for access and sharing.,None
86,sample6,7,content,NaN,None,0.739,False,False,NaN,False,text_not_found,Interested parties will be able to request data and codes at the end of the project. Such parties will be responsibl...,None
87,sample6,8,section,NaN,None,0.640,False,False,NaN,False,text_not_found,"4. Policies and provisions for re-use, re-distribution.",None
88,sample6,9,content,NaN,None,0.388,False,False,NaN,False,text_not_found,Simulation data will in essence grow to several terrabytes with an associated cost of storage. Data will be made pub...,None
89,sample6,10,section,NaN,None,0.620,False,False,NaN,False,text_not_found,5. Plans for archiving and preservation of access.,None
113,sample9,8,section,11.0,subsection,1.000,True,False,3.0,False,label_wrong,"Policies and provisions for re-use, re-distribution, and production of derivatives","Policies and provisions for re-use, re-distribution, and production of derivatives"
114,sample9,9,content,12.0,content,0.983,True,True,3.0,False,order_wrong,"All data will be stored in Dryad and will be available under a public domain, creative commons license (CC0). Note t...","All data will be stored in Dryad and will be available under a public domain, creative commons license (CC0). Note t..."
115,sample9,10,section,13.0,section,1.000,True,True,3.0,False,order_wrong,"Archiving of Data, Samples, and Other Relevant Research Products","Archiving of Data, Samples, and Other Relevant Research Products"
116,sample9,11,content,14.0,content,1.000,True,True,3.0,False,order_wrong,Laboratory notebooks and samples will be retained for a minimum of 5 years following the conclusion of the program a...,Laboratory notebooks and samples will be retained for a minimum of 5 years following the conclusion of the program a...

## Step 11 — Per-label accuracy

This answers: How well did Llama detect `document_title`, `section`, `subsection`, and `content` separately?

In [15]:
if not block_level_report.empty:
    per_label_accuracy = (
        block_level_report
        .groupby('ref_label')
        .agg(
            total_blocks=('ref_label', 'count'),
            text_found=('similar_text_found', 'sum'),
            label_correct=('label_correct', 'sum'),
            order_correct=('order_correct', 'sum')
        )
        .reset_index()
    )

    per_label_accuracy['text_match_rate'] = (per_label_accuracy['text_found'] / per_label_accuracy['total_blocks']).round(3)
    per_label_accuracy['label_accuracy'] = (per_label_accuracy['label_correct'] / per_label_accuracy['total_blocks']).round(3)
    per_label_accuracy['order_accuracy'] = (per_label_accuracy['order_correct'] / per_label_accuracy['total_blocks']).round(3)
else:
    per_label_accuracy = pd.DataFrame()

per_label_accuracy

,ref_label,total_blocks,text_found,label_correct,order_correct,text_match_rate,label_accuracy,order_accuracy
0,content,49,36,36,28,0.735,0.735,0.571
1,document_title,10,9,9,9,0.900,0.900,0.900
2,section,43,37,36,22,0.860,0.837,0.512
3,subsection,15,8,5,8,0.533,0.333,0.533

## Step 12 — Label confusion table

This answers: When Llama gave the wrong label, what did it confuse?

Example: `section → subsection`.

In [16]:
matched_blocks = block_level_report[block_level_report['similar_text_found'] == True].copy()

if not matched_blocks.empty:
    label_confusion = pd.crosstab(
        matched_blocks['ref_label'],
        matched_blocks['llama_label'],
        rownames=['Reference label'],
        colnames=['Llama label']
    )
else:
    label_confusion = pd.DataFrame()

label_confusion

Llama label      content  document_title  section  subsection
Reference label
content               36               0        0           0
document_title         0               9        0           0
section                0               0       36           1
subsection             0               0        3           5

## Step 13 — Wrong label pairs only

This gives a compact list of mistakes such as `section → subsection`.

In [17]:
wrong_label_pairs = matched_blocks[matched_blocks['ref_label'] != matched_blocks['llama_label']].copy()

if not wrong_label_pairs.empty:
    wrong_label_summary = (
        wrong_label_pairs
        .groupby(['ref_label', 'llama_label'])
        .size()
        .reset_index(name='count')
        .sort_values('count', ascending=False)
    )
else:
    wrong_label_summary = pd.DataFrame(columns=['ref_label', 'llama_label', 'count'])

wrong_label_summary

    ref_label llama_label  count
1  subsection     section      3
0     section  subsection      1

## Step 14 — Extra Llama blocks

These are blocks detected by Llama that did not match any manual/reference block.

In [18]:
extra_llama_report

,sample_id,llama_idx,llama_label,llama_text,issue
0,sample1,25,section,"Protections for privacy, rights, and confidentiality of human research participants:",extra_or_unmatched_llama_block
1,sample1,26,content,All data used in this study was de-identified prior to use.,extra_or_unmatched_llama_block
2,sample2,3,content,Data management plans should describe whether and how data generated in the course of the proposed research will be ...,extra_or_unmatched_llama_block
3,sample2,4,section,"Data Types and Sources. A brief, high-level description of the data to be generated or used through",extra_or_unmatched_llama_block
4,sample2,5,content,the course of the proposed research and which of these are considered Digital Research Data necessary to Validate th...,extra_or_unmatched_llama_block
5,sample2,6,section,"Content and Format. A statement of plans for data and metadata content and format including, where",extra_or_unmatched_llama_block
6,sample2,7,content,"applicable, a description of documentation plans, annotation of relevant software, and the rationale for the selecti...",extra_or_unmatched_llama_block
7,sample2,8,section,to be less than XX GB. Experimental techniques will generate text and Microsoft Office files and,extra_or_unmatched_llama_block
8,sample2,9,content,videos that are expected to be less than XX GB.,extra_or_unmatched_llama_block
9,sample2,10,section,Data Sharing and Data Preservation. A description of the plans for data sharing and preservation.,extra_or_unmatched_llama_block
10,sample2,11,content,"This should include, where appropriate:\n\nthe anticipated means for sharing and rationale for any restrictions on w...",extra_or_unmatched_llama_block
11,sample2,12,section,Archives).,extra_or_unmatched_llama_block
12,sample2,13,subsection,Rationale. A discussion of the rationale or justification for the proposed data management plan,extra_or_unmatched_llama_block
13,sample2,14,content,"including, for example, the potential impact of the data within the immediate field and in other fields, and any bro...",extra_or_unmatched_llama_block
14,sample2,16,subsection,Data management plans should provide a plan for making all research data displayed in,extra_or_unmatched_llama_block
15,sample2,17,content,"publications resulting from the proposed research open, machine-readable, and digitally accessible to the public at ...",extra_or_unmatched_llama_block
16,sample2,18,section,"appropriate websites (i.e. lab web sites). All of the fabrication methods, characterization results, and",extra_or_unmatched_llama_block
17,sample2,19,content,data acquired through the proposed research towards the development of the bioactive platforms will be shared with o...,extra_or_unmatched_llama_block
18,sample2,21,subsection,Data management plans should consult and reference available information about data,extra_or_unmatched_llama_block
19,sample2,22,content,"management resources to be used in the course of the proposed research. In particular, DMPs tht explicitly or implic...",extra_or_unmatched_llama_block
20,sample2,23,section,DMPs should consult and reference available information about data management resources to be,extra_or_unmatched_llama_block
21,sample2,24,content,"used in the course of the proposed research. In particular, DMPs that explicitly or implicitly commit data managemen...",extra_or_unmatched_llama_block
22,sample2,25,section,Data Repositories. Senior investigators typically archive relevant data using their own group servers.,extra_or_unmatched_llama_block
23,sample2,26,content,"Whenever possible, investigators will be encouraged to also copy data to a centralized data server for CBES investig...",extra_or_unmatched_llama_block
24,sample2,27,section,"Data Volume. Generally, the volume of data generated by CBES researchers should not prohibit their",extra_or_unmatched_llama_block
25,sample2,28,content,"deposition in available repositories. However, in cases where large volumes of data are generated (e.g., temperature...",extra_or_unmatched_llama_block
26,sample2,30,content,"Data management plans must protect confidentiality, personal privacy, Personally Identifiable Information and U.S. n...",extra_or_unmatched_llama_block
27,sample2,31,section,"conditions, and DOE orders and policies. There is no requirement to share proprietary",extra_or_unmatched_llama_block
28,sample2,32,content,data.\n\nData that may support intellectual property claims will be published only after we seek advice from the Nor...,extra_or_unmatched_llama_block
29,sample3,2,content,Roles and responsibilities The Data Management Plan should clearly articulate how the PI and co-PIs plan to manage a...,extra_or_unmatched_llama_block
30,sample3,8,content,The Data Management Plan should describe the mechanisms and formats for storing data and making them accessible to o...,extra_or_unmatched_llama_block
31,sample4,2,content,The P.I. has completed human subjects training. The research assistants will be required to complete human subjects ...,extra_or_unmatched_llama_block
32,sample4,3,section,The comparative analysis will collect data on performance and attitudes from cluster,extra_or_unmatched_llama_block
33,sample4,4,content,"participants. The performance data will include publications, citations, research grants, patents, licenses, and sta...",extra_or_unmatched_llama_block
34,sample4,5,section,Performance and survey responses will be collected from a minimum of 72 individuals affiliated,extra_or_unmatched_llama_block
35,sample4,6,content,"with interdisciplinary clusters (at least three individuals from four institutions each in six fields), and a matche...",extra_or_unmatched_llama_block
36,sample4,7,section,The members of the project team will spot check coding on a 10 percent sample of individuals,extra_or_unmatched_llama_block
37,sample4,8,content,hired through cluster programs and a 10 percent sample of individual hired through normal departmental procedures. I...,extra_or_unmatched_llama_block
38,sample4,9,section,Data will be backed up on a weekly basis on a hard drive kept in a locked cabinet in the project,extra_or_unmatched_llama_block
39,sample4,10,content,office. The data will be preserved exclusively on the two project computers and the back-up hard drive.\n\nPerforman...,extra_or_unmatched_llama_block
40,sample4,11,section,and institutions will be stripped of institutional identifications and given a letter title,extra_or_unmatched_llama_block
41,sample4,12,content,"corresponding to the institution’s name. The University of California, Riverside, for example, might be labelled “In...",extra_or_unmatched_llama_block
42,sample4,13,section,"#1461989). However, consultation with Prof. Leahey has led us to conclude that the amount of",extra_or_unmatched_llama_block
43,sample4,14,content,overlap is quite limited to the extent that it exists at all.,extra_or_unmatched_llama_block
44,sample4,15,subsection,Prof. Leahey’s work is focused on support for interdisciplinary activities on university campuses,extra_or_unmatched_llama_block
45,sample4,16,content,"and includes evidence on university investments in interdisciplinary activities. In previous work, Prof. Leahey has ...",extra_or_unmatched_llama_block
46,sample4,17,section,All data will be coded and saved on password-protected computers in the project office. No data,extra_or_unmatched_llama_block
47,sample4,18,content,will be removed from the project office during the period of the project. The only individuals with access to the co...,extra_or_unmatched_llama_block
48,sample4,19,section,No names of individuals or institutions will be used in papers prepared by the project team,extra_or_unmatched_llama_block
49,sample4,20,content,without the explicit consent of the individuals and institutions.\n\nData from the project will be preserved in data...,extra_or_unmatched_llama_block
50,sample4,21,section,the data archive will be made available on the project website to researchers who are interested,extra_or_unmatched_llama_block
51,sample4,22,content,in pursuing questions related to cluster hiring. The preservation format will be platformindependent. Following the ...,extra_or_unmatched_llama_block
52,sample4,23,section,documentation for archiving. Potential secondary users of the data include institutional,extra_or_unmatched_llama_block
53,sample4,24,content,"researchers, policy analysts, and higher education scholars.\n\nWe do not intend to generate metadata from this proj...",extra_or_unmatched_llama_block
54,sample4,25,section,"The P.I., Professor Steven Brint, will be responsible for all data collection and precautions for",extra_or_unmatched_llama_block
55,sample4,26,content,the security and confidentiality of the data.,extra_or_unmatched_llama_block
56,sample5,1,document_title,DATA MANAGEMENT PLAN,extra_or_unmatched_llama_block
57,sample5,3,content,The proposal is separated into three sections.\n\nSection 2.1 characterizes the aquifer formation that each groundwa...,extra_or_unmatched_llama_block
58,sample5,4,section,• Section 2.2 estimates groundwater components of the water budget (withdrawals and consumption),extra_or_unmatched_llama_block
59,sample5,5,content,yearly (2016-2021) at the field scale.\n\n• Section 2.3 integrates research and education through the Scientist Spot...,extra_or_unmatched_llama_block
60,sample5,7,content,"The PI and PhD student will be responsible for all data-related activities including: collection, documentation and ...",extra_or_unmatched_llama_block
61,sample5,8,section,Input data: Available data will be systematically reviewed and downloaded. These data are likely,extra_or_unmatched_llama_block
62,sample5,9,content,available in the form of Microsoft Access files or Microsoft Excel spreadsheets; shapefiles or raster files;\n\nor t...,extra_or_unmatched_llama_block
63,sample5,10,section,Produced Data: Datasets will be produced in Sections 2.1-2.3 of the proposal. These datasets will be,extra_or_unmatched_llama_block
64,sample5,11,content,"formatted and shared in an open format (e.g., CSV) or in illustrator files (i.e., cross sections).",extra_or_unmatched_llama_block
65,sample5,15,content,"Raw data: Detailed information about how the data were obtained, including detailed contact information or websites ...",extra_or_unmatched_llama_block
66,sample5,16,section,Scripts and code for analyses: All scripts and code will be archived in supplementary information,extra_or_unmatched_llama_block
67,sample5,17,content,appendices in publications as well as uploaded to Zenodo through the Dryad repository submission process along with ...,extra_or_unmatched_llama_block
68,sample5,18,section,"Scientist spotlight: All scientist spotlight biographies, assignments, and open-access readings will be",extra_or_unmatched_llama_block
69,sample5,19,content,"posted to an online Dashboard associated with the PI’s website, which is updated bi-monthly.",extra_or_unmatched_llama_block
70,sample5,20,section,Workshop frameworks: Workshop material will be shared with UCSB’s Diversity Committee through,extra_or_unmatched_llama_block
71,sample5,21,content,"Google Drive; if workshop materials are fully supported by the Diversity Committee, these materials will also be sha...",extra_or_unmatched_llama_block
72,sample6,2,section,"1. Types of data. The bulk of the data generated in this project will be 1, 2, 3, and 4",extra_or_unmatched_llama_block
73,sample6,4,section,2. Data and metadata standards. The PI’s research group will adopt the longstanding,extra_or_unmatched_llama_block
74,sample6,5,content,"practice that all generated data should be straightforwardly reproducible. Thus, codes are stored within the same di...",extra_or_unmatched_llama_block
75,sample6,6,section,3. Policies for access and sharing. Interested parties will be able to request data and codes at,extra_or_unmatched_llama_block
76,sample6,7,content,the end of the project. Such parties will be responsible for their own version control and execution.,extra_or_unmatched_llama_block
77,sample6,8,section,"4. Policies and provisions for re-use, re-distribution. Simulation data will in essence grow to",extra_or_unmatched_llama_block
78,sample6,9,content,several terrabytes with an associated cost of storage. Data will be made publicly available upon request at the end ...,extra_or_unmatched_llama_block
79,sample6,10,section,5. Plans for archiving and preservation of access. Local data will be archived on the group’s,extra_or_unmatched_llama_block
80,sample9,2,content,ELECTRODES,extra_or_unmatched_llama_block
81,sample9,9,section,extensions (and conditions under which they can use and modify the code) will be uploaded to the,extra_or_unmatched_llama_block
82,sample9,10,content,CASM software website: https://prisms-center.github.io/CASMcode_docs/.,extra_or_unmatched_llama_block

## Step 15 — Save all reports

In [19]:
summary_path = output_dir / 'summary_report.csv'
block_path = output_dir / 'block_level_report.csv'
problem_path = output_dir / 'problem_blocks_report.csv'
per_label_path = output_dir / 'per_label_accuracy.csv'
confusion_path = output_dir / 'label_confusion_matrix.csv'
wrong_pairs_path = output_dir / 'wrong_label_pairs.csv'
extra_path = output_dir / 'extra_llama_blocks.csv'

summary_report.to_csv(summary_path, index=False)
block_level_report.to_csv(block_path, index=False)
problem_blocks.to_csv(problem_path, index=False)
per_label_accuracy.to_csv(per_label_path, index=False)
label_confusion.to_csv(confusion_path)
wrong_label_summary.to_csv(wrong_pairs_path, index=False)
extra_llama_report.to_csv(extra_path, index=False)

print('Saved reports:')
for p in [summary_path, block_path, problem_path, per_label_path, confusion_path, wrong_pairs_path, extra_path]:
    print(' -', p)

Saved reports:
 - c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple\summary_report.csv
 - c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple\block_level_report.csv
 - c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple\problem_blocks_report.csv
 - c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple\per_label_accuracy.csv
 - c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple\label_confusion_matrix.csv
 - c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple\wrong_label_pairs.csv
 - c:\Users\Nahid\dmpbridge\data\block_comparison_reports_simple\extra_llama_blocks.csv

## Step 16 — Simple interpretation guide

Use this wording in your results:

- **Text Match Rate** = how many manual blocks were found by Llama.
- **Label Accuracy** = how many manual blocks were found with the correct label.
- **Order Accuracy** = how many manual blocks were found in the correct/near-correct document order.
- **Label Confusion Table** = shows which labels Llama confused, such as `section → subsection`.

For each sample, your main conclusion should be:

> Llama found the text well / not well, labeled the blocks correctly / incorrectly, and preserved / did not preserve document order.